version: "3.7"
services:
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: api
      POSTGRES_DB: skp-data
      ALLOW_IP_RANGE: 0.0.0.0/0
    volumes:
      - ./app:/var/lib/postgresql/data
    ports:
      - "6001:5432"
    container_name: skp-data
  skp-backend:
    container_name: skp-backend
    build: .
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    image: skp-backend
    depends_on:
      - db
    ports:
      - "5001:5001"
    command: yarn develop

volumes:
  node_modules:

networks:
  typeorm: